// This file is auto-generated by @hey-api/openapi-ts

export type MailcoachEmailList = {
    uuid: string;
    name: string;
    created_at: string;
    updated_at: string;
};

export type GetMailingListsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/MailingLists';
};

export type GetMailingListsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetMailingListsResponses = {
    /**
     * OK
     */
    200: Array<MailcoachEmailList>;
};

export type GetMailingListsResponse = GetMailingListsResponses[keyof GetMailingListsResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44368' | (string & {});
};